### ISSUE TITLE
Final Results

### ISSUE THREAD

**Issue by nickjhathaway** [lerch-a/HaplotypR#13]
Hi, 
I was able to run through the tutorial on the github main page but I was wondering what files from the final directories we should use for further downstream analysis?  

Thanks! 

- Nick

**Comment by lerch-a** [comment]
Hi Nick,
sorry for the slow response.
The tables starting with finalHaplotypeList_... in the top folder should be used for further downstream analysis.
Anita

**Comment by nickjhathaway** [comment]
So those tables just have the number of haplotypes found vs noise but I was wondering what haplotype sequences we should use. Thanks!

**Comment by lerch-a** [comment]
There is also a file for each marker in the same folder
markerID_HaplotypeSeq_....fasta
containing the corresponding sequence for each Haplotype (only with the newer versions). 
This file is only provided if you provided a referenceSeq during createFinalHaplotypTable().

It is important to note that HaplotypR is build mainly for non-length-polymorphic marker.
You can use it also us it with length-polymorphic marker, but filtering after is not as good.

Thanks for the question. I will address the feedback for future development.

**Comment by nickjhathaway** [comment]
So when I run through the example on GitHub page those files are empty (csp_HaplotypeSeq_bind190_120.fasta and cpmp_HaplotypeSeq_bind190_120.fasta). When I run 

```
packageVersion("HaplotypR")
```
I get ‘0.3.2’ so I think I'm using the newest version, is there something additional or extra flag I should set to populate those files? 

Thanks!

**Comment by lerch-a** [comment]
I just checked the example. It looks like there was a bug introduced with the last changes. I'll take care of it.

**Comment by lerch-a** [comment]
Ok, the newest version fix that bug. We fixed a very old bug, but forgot also to adjust the marker file. So make sure you download and load the example data again.

Please, let me know if you find more issues. And thanks a lot for the feedback.
