### ISSUE TITLE
a bug and a question

### ISSUE THREAD

**Issue by EdgarNietoFungi** [lerch-a/HaplotypR#15]
**I found these bugs, misspellings, or replacement during the script:**

procReads <- mergeAmpliconReads(as.character(dePlexMarker$FileR1), as.character(dePlexMarker$FileR2), outProcFiles)
procReads <- cbind(dePlexMarker[,c("SampleID", "SampleName","BarcodePair", "MarkerID")], procReadsMerge)

**I think it should be as this, instead:** 

procReadsMerge <- mergeAmpliconReads(as.character(dePlexMarker$FileR1), as.character(dePlexMarker$FileR2), outProcFiles)
procReads <- cbind(dePlexMarker[,c("SampleID", "SampleName","BarcodePair", "MarkerID")], procReadsMerge)

**That would be nice and helpful if for all the script you reformat the code Ctrl+Shift+A/ Cmd+Shift+A**

**I have a question, for “Calculate mismatch rate and call SNPs” and “Call Haplotypes” what should be my **outputDir**, I having bugs in both calls**

**Thank you in advance,**

**Comment by lerch-a** [comment]
1.) Thanks for letting me know about the typo. It should be fixed now.

2.) What do yo mean with "reformatting the code Ctrl+Shift+A/ Cmd+Shift+A"?
The code is wrapped with ```R tags.

3.) The outputDir is defined at the beginning of the example (see below). It is a folder in your working directory or somewhere else on your computer. You can define it differently as "exampleHapotypR". Make sure you are not using "~" in the path, as it will fail during calling a third platform software.

# Define output directory 
outputDir <- "exampleHaplotypR"

**Comment by lerch-a** [comment]
Bug solved.
