### ISSUE TITLE
Marker file reference

### ISSUE THREAD

**Issue by dcm9123** [lerch-a/HaplotypR#2]
Hi! I was wondering if the reference column that you have in your marker file refers to an example of a read that has the primers in it? Or what does this reference stand for? Can I upload a file with only the forward and reverse primers without the reference?

Thanks!

**Comment by lerch-a** [comment]
It refers to the reference genome sequence for example the 3D7 reference strain genome sequence.
You need this for pairwise comparison of the amplicon to the reference, which is done to call SNPs.
