### ISSUE TITLE
Empty fasta file.

### ISSUE THREAD

**Issue by dcm9123** [lerch-a/HaplotypR#3]
Hi! I'm having a problem while running my gene markers. I've uploaded my files in a similar way as you have it in your test folder, however when I encounter the trimming process I get null values when trying to save as a fasta file:

``
> numNtF <- 190
> numNtR <- 120
> postfix <- sprintf("_bind%.0f_%.0f", numNtF, numNtR)
> # Adjust reference to trim options and save as fasta file
> refSeq <- as.character(markerTab$ReferenceSequence)
> refSeq <- DNAStringSet(paste(substr(refSeq, 1,numNtF), substr(refSeq, nchar(refSeq)+1-numNtR, nchar(refSeq)), sep=""))
> names(refSeq) <- markerTab$MarkerID
> lapply(seq_along(refSeq), function(i){
+   writeFasta(refSeq[i], file.path(outputDir, paste(names(refSeq)[i], postfix, ".fasta", sep="")))
+ })
[[1]]
NULL

[[2]]
NULL
``

This ultimately leads to the following message:
`Processing file NA and NA1
Error in open.connection(con, "rb") : cannot open the connection
In addition: Warning message:
In open.connection(con, "rb") :
  cannot open file 'NA': No such file or directory`

Do you know what could it be?

Thanks in advance

**Comment by lerch-a** [comment]
Hi, the error suggest that something with our filename is not correct.
Can you please check the output if you execute in R (after you got the error): 

outputDir
names(refSeq)
markerTab$MarkerID
postfix

as well as executing:
dir.exists(outputDir)
refSeq

How experienced are you with R?

**Comment by dcm9123** [comment]
Hi Anita! Thanks a lot for your fast response. Absolutely, the output is as follows:
```
outputDir = "/Users/Danniel/exampleHaplotypR"
names(refSeq) = "msp1" "msp2"
markerTab$MarkerID = "msp1" "msp2"
postfix = "_bind190_120"
```

when executing `dir.exists(outputDir),` the result is TRUE
when executing `refSeq` by itself I get:

`A DNAStringSet instance of length 2
    width seq                                                              names               
[1]   310 GACAGGTTATAGTTTATTTCAAAAGGAAAAA...ATTAAATTTAACATTGATAGTTTATTTACT msp1
[2]   310 AAATTTCTTTATTTTTGTTACCTTTAATATT...CTTCAGAAAATCCAAATCATAAAAATGCCG msp2
`

I am somewhat familiar with R, I can move around and do some coding. Thanks a lot for your help,

Daniel

**Comment by lerch-a** [comment]
It is unclear to me why the following lines are not working, based on your output.

lapply(seq_along(refSeq), function(i){
	writeFasta(refSeq[i], file.path(outputDir, paste(names(refSeq)[i], postfix, ".fasta", sep="")))
})

Your error message implies that the filename created by executing 
“file.path(outputDir, paste(names(refSeq)[i], postfix, ".fasta", sep=""))” 
is NA!

Can you execute the lines without the lapply call?
`writeFasta(refSeq[1], file.path(outputDir, paste(names(refSeq)[1], postfix, ".fasta", sep="")))`
`writeFasta(refSeq[2], file.path(outputDir, paste(names(refSeq)[2], postfix, ".fasta", sep="")))`


Do you have the Bioconductor ShortRead package installed and  loaded?
`if (!requireNamespace("BiocManager", quietly = TRUE))`
`install.packages("BiocManager")`
`BiocManager::install("ShortRead")`
`library(ShortRead)`

What the output of `sessionInfo()`?

**Comment by dcm9123** [comment]
Hi Anita,

Thanks for your response. I've been looking into it, and after running them individually I am still getting the NA (without lapply). Could it be because my data has been previously demultiplexed and trimmed? I also noticed that in your example files you use one single file that represents has all of your reads across all of your samples, correct? In my case, I only uploaded the data (forward and reverse trimmed reads) for one sample. The output from sessionInfo() is the following:
```

R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] git2r_0.25.2                usethis_1.5.0               devtools_2.0.2             
 [4] ShortRead_1.40.0            GenomicAlignments_1.18.1    SummarizedExperiment_1.12.0
 [7] DelayedArray_0.8.0          matrixStats_0.54.0          Biobase_2.42.0             
[10] Rsamtools_1.34.1            GenomicRanges_1.34.0        GenomeInfoDb_1.18.2        
[13] Biostrings_2.50.2           XVector_0.22.0              IRanges_2.16.0             
[16] S4Vectors_0.20.1            BiocParallel_1.16.6         BiocGenerics_0.28.0        
[19] shiny_1.3.2                 HaplotypR_0.3              

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1             lattice_0.20-38        prettyunits_1.0.2      ps_1.3.0              
 [5] rprojroot_1.3-2        assertthat_0.2.1       digest_0.6.18          mime_0.6              
 [9] R6_2.4.0               plyr_1.8.4             backports_1.1.4        ggplot2_3.1.1         
[13] pillar_1.4.0           zlibbioc_1.28.0        rlang_0.3.4            lazyeval_0.2.2        
[17] rstudioapi_0.10        callr_3.2.0            Matrix_1.2-17          desc_1.2.0            
[21] RCurl_1.95-4.12        munsell_0.5.0          compiler_3.5.2         httpuv_1.5.1          
[25] pkgconfig_2.0.2        pkgbuild_1.0.3         htmltools_0.3.6        tidyselect_0.2.5      
[29] tibble_2.1.1           GenomeInfoDbData_1.2.0 withr_2.1.2            crayon_1.3.4          
[33] dplyr_0.8.0.1          later_0.8.0            bitops_1.0-6           grid_3.5.2            
[37] xtable_1.8-4           gtable_0.3.0           magrittr_1.5           scales_1.0.0          
[41] cli_1.1.0              hwriter_1.3.2          fs_1.3.1               remotes_2.0.4         
[45] promises_1.0.1         latticeExtra_0.6-28    RColorBrewer_1.1-2     tools_3.5.2           
[49] glue_1.3.1             purrr_0.3.2            pkgload_1.0.2          processx_3.3.1        
[53] yaml_2.2.0             colorspace_1.4-1       sessioninfo_1.1.1      memoise_1.1.0  

```
As you can see, I have the shortRead package. I am also attaching the files that I am using to work, maybe it is because I have only one sample and it has been demultiplexed and trimmed?

Thanks for looking at it,

Daniel.

[extdata.zip](https://github.com/lerch-a/HaplotypR/files/3171286/extdata.zip)

**Comment by lerch-a** [comment]
Sorry, I'm working on it. Your installation of R is more current than my one. I first need to update.

**Comment by dcm9123** [comment]
.

**Comment by lerch-a** [comment]
Just to clarify, you can not run the example succesfully. Is that correct?

**Comment by dcastaneda5** [comment]
I can run the example data that you provided, but not my own data. Do you
think its because my data has been already demultiplexed?

thanks


[image: photo]
*Daniel Castaneda Mogollon*
Ph.D Microbiology and Infectious Diseases, Pillai Research Lab

+1 403 484 9019 | daniel.castanedamogo@ucalgary.ca

dann.dignus.discere@gmail.com
1403 29 St NW, Calgary, AB T2N 2T9
<http://www.linkedin.com/mynetwork/add-connections/>
"The greatest enemy of knowledge is not ignorance, it is the illusion of
knowledge." -Daniel J. Boorstin
Create your own email signature
<https://www.wisestamp.com/signature-in-email?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own>

**Comment by lerch-a** [comment]
First, this pipeline is not designed to run only a single sample as it uses population information for SNP calling and haplotype filtering. 
--> What do you like to do with just one sample? 
It also looks as you would like to run marker msp1 and msp2 which are length-polymorphic. The pipeline should run for those type of marker, but you need special configuration. It is also not as well tested.

Second, your "markerFile_msp.txt" is not formatted in the right way. Your reference sequence is split over multiple lines. I attached a corrected version.
[markerFile_msp.txt](https://github.com/lerch-a/HaplotypR/files/3199695/markerFile_msp.txt)
I do get the reference fasta files with the corrected markerFile and the following code:
```
primerFile <- "markerFile_msp.txt"
numNtF <- 190
numNtR <- 120
postfix <- sprintf("_bind%.0f_%.0f", numNtF, numNtR)

markerTab <- read.delim(primerFile, stringsAsFactors=F)
refSeq <- as.character(markerTab$ReferenceSequence)

refSeq <- DNAStringSet(paste(substr(refSeq, 1,numNtF), substr(refSeq, nchar(refSeq)+1-numNtR, nchar(refSeq)), sep=""))
names(refSeq) <- markerTab$MarkerID
lapply(seq_along(refSeq), function(i){
  writeFasta(refSeq[i], file.path(outputDir, paste(names(refSeq)[i], postfix, ".fasta", sep="")))
})
```


Third, if you skip the demultiplex steps, you need to create the output data.frame from the demultiplex steps manually, e.g.
```
dePlexMarker <- data.frame(BarcodePair=NA, SampleID="test1", SampleName="test", 
                           MarkerID="msp1", numReadIn=NA, numReadOut=NA, 
                           FileR1=reads[1], FileR2=reads[2])
```

**Comment by dcastaneda5** [comment]
Dear Anita,

Thank you for your reply and for the corrections you have made. I was just
testing the pipeline with only one sample before I added the rest of my
data. I will be running it with these new suggestions.

Thanks for your help!

[image: photo]
*Daniel Castaneda Mogollon*
Ph.D Microbiology and Infectious Diseases, Pillai Research Lab

+1 403 484 9019 | daniel.castanedamogo@ucalgary.ca

dann.dignus.discere@gmail.com
1403 29 St NW, Calgary, AB T2N 2T9
<http://www.linkedin.com/mynetwork/add-connections/>
"The greatest enemy of knowledge is not ignorance, it is the illusion of
knowledge." -Daniel J. Boorstin
Create your own email signature
<https://www.wisestamp.com/signature-in-email?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own>
